---
name: Converts, prints, validates
author: Yevhen Fabizhevskyi
description: It is used for tests only.
branding:
  icon: copy
  color: green
inputs:
  from:
    description: formats to convert from
    required: true
  to:
    description: formats to convert to
    required: true
runs:
  using: "composite"
  steps:
    - name: Convert ${{ inputs.from }} to ${{ inputs.to }}
      uses: ./
      id: convert
      with:
        source-pattern: tests/expected-${{ inputs.from }}.${{ inputs.from }}
        to: ${{ inputs.to }}
    - name: Print resulting ${{ inputs.to }} file
      env:
        INPUT_FROM: "${{ inputs.from }}"
        INPUT_TO: "${{ inputs.to }}"
        STEP_CONVERT_OUTPUT_RESULT_PATH: "${{ steps.convert.outputs.result-path }}"
      run: cat ${STEP_CONVERT_OUTPUT_RESULT_PATH}/expected-${INPUT_FROM}.${INPUT_TO}
      shell: sh
    - name: Validate resulting ${{ inputs.to }} file
      env:
        INPUT_FROM: "${{ inputs.from }}"
        INPUT_TO: "${{ inputs.to }}"
        STEP_CONVERT_OUTPUT_RESULT_PATH: "${{ steps.convert.outputs.result-path }}"
      run: |
        expected_file_path="tests/expected-${INPUT_TO}.${INPUT_TO}"
        actual_file_path="${STEP_CONVERT_OUTPUT_RESULT_PATH}/expected-${INPUT_FROM}.${INPUT_TO}"
        cmp -s "${expected_file_path}" "${actual_file_path}" \
          || diff --strip-trailing-cr "${expected_file_path}" "${actual_file_path}"
      shell: sh
