---
name: 'Action-helper for functional tests'
author: Yevhen Fabizhevskyi
description: 'This action encapsulates the logic of running the same test on multiple environments'
inputs:
  from:
    description: 'Format of a file. Possible values: json, xml, yaml, props.'
    required: true
  to:
    description: 'Format of a file as a result. Possible values: json, xml, yaml, props.'
    required: true
  os:
    description: 'OS on which this test is running on.'
runs:
  using: 'composite'
  steps:
    - name: Prepare
      run: |
        echo 's:' > expected.yaml
        echo '  v: "1"' >> expected.yaml
        echo '  m:' >> expected.yaml
        echo '    - t1' >> expected.yaml
        echo '    - t2' >> expected.yaml
        echo '{' > expected.json
        echo '  "s": {' >> expected.json
        echo '    "v": "1",' >> expected.json
        echo '    "m": [' >> expected.json
        echo '      "t1",' >> expected.json
        echo '      "t2"' >> expected.json
        echo '    ]' >> expected.json
        echo '  }' >> expected.json
        echo '}' >> expected.json
        echo '<s>' > expected.xml
        echo '  <v>1</v>' >> expected.xml
        echo '  <m>t1</m>' >> expected.xml
        echo '  <m>t2</m>' >> expected.xml
        echo '</s>' >> expected.xml
        echo 's.v = 1' > expected.props
        echo 's.m.0 = t1' >> expected.props
        echo 's.m.1 = t2' >> expected.props
      shell: sh
    - name: Convert
      uses: ./
      id: convert
      with:
        input: expected.${{ inputs.from }}
        from: ${{ inputs.from }}
        to: ${{ inputs.to }}
    - name: Save result
      run: echo '${{ steps.convert.outputs.output }}' > actual.${{ inputs.to }}
      shell: sh
    - name: Print actual file
      run: cat actual.${{ inputs.to }}
      shell: sh
    - name: Install dependencies
      if: ${{ inputs.os == 'centos' }}
      run: |
        sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
        sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*
        yum update -y
        yum install diffutils
      shell: sh
    - name: Validate
      run: cmp -s "expected.json" "actual.${{ inputs.to }}" || diff "expected.${{ inputs.to }}" "actual.${{ inputs.to }}"
      shell: sh
    - name: Clean up
      run: |
        rm -f expected.yaml
        rm -f expected.json
        rm -f expected.xml
        rm -f expected.props
        rm -f actual.${{ inputs.to }}
      shell: sh
