---
name: Update License

on: # yamllint disable-line rule:truthy
  schedule:
    - cron: "0 5 1 1 *"

jobs:
  update-license:
    name: LICENSE
    uses: fabasoad/reusable-workflows/.github/workflows/wf-update-license.yml@main
    secrets: inherit # pragma: allowlist secret
